### ISSUE TITLE
最新浏览器打不开环线

### ISSUE THREAD

**Issue by beijing-subway** [railmapgen/rmg#331]
我用的QQ浏览器，更新到最新版本，环线仍旧打不开。
at v (https://railmapgen.github.io/rmg/static/js/railmapSHMetro.7a4eef55.chunk.js:1:6958)
    at https://railmapgen.github.io/rmg/static/js/railmapSHMetro.7a4eef55.chunk.js:1:15340
    at Suspense
    at svg
    at c (https://railmapgen.github.io/rmg/static/js/AppRoot.df29b9ba.chunk.js:1:3968)
    at n (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:2696)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326549
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:147924
    at z (https://railmapgen.github.io/rmg/static/js/AppRoot.df29b9ba.chunk.js:1:5151)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326549
    at section
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326549
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:147924
    at div
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326549
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:147924
    at div
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326549
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:147924
    at div
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326549
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:147924
    at He (https://railmapgen.github.io/rmg/static/js/AppRoot.df29b9ba.chunk.js:1:78424)
    at n (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:2696)
    at Suspense
    at A (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:562343)
    at R (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:561602)
    at c (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:555076)
    at f (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:188891)
    at b (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:133168)
    at d (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:326760)
    at A (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:296092)
    at https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:136189
    at Yr (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:255426)
    at c (https://railmapgen.github.io/rmg/static/js/main.808090bf.js:2:552724)
    at w

**Comment by thekingofcity** [comment]
嗨，你可以尝试最新版本的Firefox, Chrome, 或Edge。这或许是由于QQ浏览器内核尚未更新到主流版本的原因。

**Comment by wongchito** [comment]
> 也许我们需要Browserstack，来测试兼容性（caniuse就是这么做的）

我們*不會*改變源程式碼以提升其相容性，但我們會嘗試於轉譯過程中採用Polyfill以儘可能擴大相容性（見#314）。

**Comment by 52PD** [comment]
> 嗨，你可以尝试最新版本的Firefox, Chrome, 或Edge。这或许是由于QQ浏览器内核尚未更新到主流版本的原因。

差了一下，QQ浏览器的内核确实老了（目前QQ浏览器用的还是Chromium 70内核，而Chrome的官方最新版（包括Chromium内核）是Chrome/Chromium 100😂
