### ISSUE TITLE
支线问题

### ISSUE THREAD

**Issue by HarikerMumu** [railmapgen/rmg#366]
在以港铁风格创建支线后发生故障无法生成站台门路线图
报错如下：

TypeError: Cannot read properties of undefined (reading 'indexOf')

    at O (https://railmapgen.github.io/rmg/static/js/railmapMTR.34348cf6.chunk.js:1:15554)
    at Suspense
    at svg
    at c (https://railmapgen.github.io/rmg/static/js/AppRoot.9f51c8d8.chunk.js:1:8547)
    at n (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:2800)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:328814
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:150189
    at b (https://railmapgen.github.io/rmg/static/js/AppRoot.9f51c8d8.chunk.js:1:9730)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:328814
    at section
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:328814
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:150189
    at div
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:328814
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:150189
    at div
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:328814
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:150189
    at div
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:328814
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:150189
    at pe (https://railmapgen.github.io/rmg/static/js/AppRoot.9f51c8d8.chunk.js:1:80641)
    at n (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:2800)
    at Suspense
    at A (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:564608)
    at R (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:563867)
    at c (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:557341)
    at f (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:191156)
    at b (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:135433)
    at d (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:329025)
    at A (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:298357)
    at https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:138454
    at Yr (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:257691)
    at c (https://railmapgen.github.io/rmg/static/js/main.67f9dfbf.js:2:554989)
    at b

使用环境：microsoft edge 版本102.0.1245.14

**Comment by wongchito** [comment]
你好 @HarikerMumu ，

請問閣下能否提供重現該問題之步驟？

於本機測試中，我暫時找到**另一個**關於新增支綫之問題 - 當支綫兩端設定為「路綫左端」及「路綫右端」，所新增之支綫不能被正常顯示，所新增之車站亦無法移除，但該問題並不會導致閣下提供之詳情之情況。該問題亦已於 968592b6 修復。
