### ISSUE TITLE
切换风格后报错

### ISSUE THREAD

**Issue by rainydew** [railmapgen/rmg#377]
Something went wrong.
详情
TypeError: Cannot read properties of undefined (reading '0')

    at d (https://railmapgen.github.io/rmg/static/js/destinationSHMetro.dad6c3c9.chunk.js:1:2177)
    at g
    at f (https://railmapgen.github.io/rmg/static/js/destinationSHMetro.dad6c3c9.chunk.js:1:522)
    at Suspense
    at svg
    at c (https://railmapgen.github.io/rmg/static/js/AppRoot.92413c98.chunk.js:1:8650)
    at n (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:2800)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:150446
    at b (https://railmapgen.github.io/rmg/static/js/AppRoot.92413c98.chunk.js:1:9833)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336559
    at section
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:150446
    at div
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:150446
    at div
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:150446
    at div
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:150446
    at pe (https://railmapgen.github.io/rmg/static/js/AppRoot.92413c98.chunk.js:1:81222)
    at n (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:2800)
    at Suspense
    at A (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:586395)
    at R (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:585654)
    at c (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:579128)
    at https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:263158
    at m (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:197461)
    at v (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:134588)
    at d (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:336770)
    at A (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:306379)
    at v (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:197987)
    at go (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:263761)
    at c (https://railmapgen.github.io/rmg/static/js/main.e4e8b027.js:2:576776)
    at b
Please try to refresh or re-import your configuration files. If the issue still persists, please consider upgrading your browser or submit an issue in [GitHub Issue](https://github.com/railmapgen/rmg/issues) with the detail shown above.

請嘗試重新整理或重新上載設定檔。如果問題仍然存在，請考慮更新你的瀏覽器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一個Issue並附上詳情。

请尝试刷新或或重新上传配置文件。如果问题仍然存在，请考虑更新您的浏览器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一个Issue并附上详情。

对源文件(港铁风格)上传后，切换为上海地铁风格则报以上错误，没有看出来原因，可以看下吗
```json
{"svg_height":320,"padding":7.05352436628492,"y_pc":40,"branch_spacing":69.84,"theme":["other","other","#0003F0","#fff"],"direction":"r","current_stn_idx":"l1mz","platform_num":"1","stn_list":{"linestart":{"parents":[],"children":["l1mz"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"num":"00","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"lineend":{"parents":["iwf6"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"num":"00","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"l1mz":{"parents":["linestart"],"children":["a398","p2ty"],"name":["雪松路","Tsusong Road"],"branch":{"left":[],"right":["through","p2ty"]},"num":"22","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["other","other","#BEEE04","#000","13号线","Line 13"]]]},"services":["local"],"facility":"","secondaryName":false},"iwf6":{"children":["lineend"],"parents":["i4ka","3l9j"],"name":["紫林路","Dziglin Road"],"branch":{"left":["through","3l9j"],"right":[]},"num":"23","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["other","other","#88FFC8","#000","17号线","Line 17"]]]},"services":["local"],"facility":"","secondaryName":false},"6pnf":{"name":["雪花塘","Siewa Tong"],"secondaryName":false,"num":"00","services":["local"],"parents":["08jy"],"children":["5prf"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"p2ty":{"name":["吉祥区政府","Johnaon Government"],"secondaryName":false,"num":"00","services":["local"],"parents":["l1mz"],"children":["4of2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#FF6000","#fff","7号线","Line 7"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"5prf":{"name":["二环北桥","North Bridge"],"secondaryName":false,"num":"00","services":["local"],"parents":["6pnf"],"children":["azn8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#78FFFf","#000","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"azn8":{"name":["临港客运站","Harboring Bus Terminal"],"secondaryName":false,"num":"00","services":["local"],"parents":["5prf"],"children":["611y"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#c07f40","#fff","21号线","Line 21"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"611y":{"name":["穆青路","Mahchin Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["azn8"],"children":["e10o"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#78FFFf","#000","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"e10o":{"name":["电视台","TV Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["611y"],"children":["t3vy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"i4ka":{"name":["商贸城","Commercial Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["gmn5"],"children":["iwf6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#00C003","#fff","2号线","Line 2"],["other","other","#8800F8","#fff","31号线","Line 31"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"qj0i":{"name":["大学城西","PHEMC West"],"secondaryName":false,"num":"00","services":["local"],"parents":["mphv"],"children":["e3jg"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"mphv":{"name":["天平小区","Libra Block"],"secondaryName":false,"num":"00","services":["local"],"parents":["oop5"],"children":["qj0i"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#A000A0","#fff","5号线","Line 5"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"oop5":{"name":["东方美食城","Tunphoon Food Court"],"secondaryName":false,"num":"00","services":["local"],"parents":["t3vy"],"children":["mphv"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"t3vy":{"name":["鱼乐园","Venaring"],"secondaryName":false,"num":"00","services":["local"],"parents":["e10o"],"children":["oop5"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#E8F00e","#000","3号线","Line 3"],["other","other","#7FFF58","#000","30号线","Line 30"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"gmn5":{"name":["沙坡头","Sharpor Front"],"secondaryName":false,"num":"00","services":["local"],"parents":["e3jg"],"children":["i4ka"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#008480","#fff","11号线","Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"e3jg":{"name":["国际大学","International University"],"secondaryName":false,"num":"00","services":["local"],"parents":["qj0i"],"children":["gmn5"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#C4C000","#000","12号线","Line 12"],["other","other","#B80038","#fff","23号线","Line 23"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"a398":{"name":["州体育场","Statal Gym"],"secondaryName":false,"num":"00","services":["local"],"parents":["l1mz"],"children":["08jy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#E8C172","#000","10号线","Line 10"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"08jy":{"name":["一中","The 1st High School"],"secondaryName":false,"num":"00","services":["local"],"parents":["a398"],"children":["6pnf"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#00C003","#fff","2号线","Line 2"],["other","other","#8800F8","#fff","31号线","Line 31"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"3l9j":{"name":["白桦村","Birch Village"],"secondaryName":false,"num":"00","services":["local"],"parents":["zhdm"],"children":["iwf6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#A000A0","#fff","5号线","Line 5"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"zhdm":{"name":["海石湾","Haise Bay"],"secondaryName":false,"num":"00","services":["local"],"parents":["mvx6"],"children":["3l9j"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#F00200","#fff","4号线","Line 4"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"mvx6":{"name":["穆萨尔维大学","Musarvi University"],"secondaryName":false,"num":"00","services":["local"],"parents":["1dim"],"children":["zhdm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#E8C172","#000","10号线","Line 10"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"1dim":{"name":["大清真寺","The Great Mosque"],"secondaryName":false,"num":"00","services":["local"],"parents":["iraa"],"children":["mvx6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"iraa":{"name":["铁匠子","Blacksmith"],"secondaryName":false,"num":"00","services":["local"],"parents":["pus1"],"children":["1dim"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"pus1":{"name":["古马廊","Ancient Stable"],"secondaryName":false,"num":"00","services":["local"],"parents":["02pr"],"children":["iraa"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#F00200","#fff","4号线","Line 4"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"02pr":{"name":["火车南站","South Railway Station\\可出闸换乘36号线"],"secondaryName":false,"num":"00","services":["local"],"parents":["lcvx"],"children":["pus1"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#E8F00e","#000","3号线","Line 3"],["other","other","#BEEE04","#000","13号线","Line 13"],["other","other","#FCDF90","#000","19号线","Line 19"],["other","other","#7FFF58","#000","30号线","Line 30"]],[]],"tick_direc":"r","paid_area":true,"osi_names":[["南站枢纽","South Station"]]},"facility":""},"lcvx":{"name":["长巷子","Allenare"],"secondaryName":false,"num":"00","services":["local"],"parents":["ags7"],"children":["02pr"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"ags7":{"name":["环路口","Ring Cross"],"secondaryName":false,"num":"00","services":["local"],"parents":["xjeq"],"children":["lcvx"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#c07f40","#fff","21号线","Line 21"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"xjeq":{"name":["秀山公园","Siewzan Hill Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["f0tq"],"children":["ags7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#FF6000","#fff","7号线","Line 7"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"f0tq":{"name":["黄金市场","Golden Market"],"secondaryName":false,"num":"00","services":["local"],"parents":["4of2"],"children":["xjeq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"4of2":{"name":["二环南桥","South Bridge"],"secondaryName":false,"num":"00","services":["local"],"parents":["p2ty"],"children":["f0tq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#008480","#fff","11号线","Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""}},"line_name":["1号线","Line 1"],"psd_num":"3","line_num":"TP","info_panel_type":"sh","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":["内环方向","clockwise"]},"svgWidth":{"destination":1080,"runin":1100,"railmap":3200,"indoor":3200},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false}}
```

**Comment by thekingofcity** [comment]
嗨，感谢您汇报的问题。不过当前上海风格暂不支持闭合的下方支线，即支线的左右两端都接入主线的情况。您无法在上海风格中创建此类型的线路。您可以尝试闭合的上方支线，但我无法确认此种情况是否被支持。如果您如需要上海风格中环线的样式，可以参考上海地铁4号线的模板，谢谢。

**Comment by rainydew** [comment]
ok，主要是从报错上看不出原因。这个图是从v4过来(那时不支持环线，所以只能用这种效果模拟)，要迁移成环线的。这样就清楚了，不过目前没办法把整条线路迁移过来(或者把支线切割，拼接为主线，只好重写一半的车站)
