### ISSUE TITLE
5.2.8模板环线显示

### ISSUE THREAD

**Issue by 749207106** [railmapgen/rmg#385]
5.2.8模板环线显示：Something went wrong.
详细信息
Please try to refresh or re-import your configuration files. If the issue still persists, please consider upgrading your browser or submit an issue in [GitHub Issue](https://github.com/railmapgen/rmg/issues) with the detail shown above.

請嘗試重新整理或重新上載設定檔。如果問題仍然存在，請考慮更新你的瀏覽器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一個Issue並附上詳情。

请尝试刷新或或重新上传配置文件。如果问题仍然存在，请考虑更新您的浏览器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一个Issue并附上详情。
以及
Something went wrong.
详细信息
TypeError: Object.values(...).filter(...).map(...).at is not a function

    at p (https://railmapgen.github.io/rmg/static/js/2977.ac9e0378.chunk.js:1:10709)
    at https://railmapgen.github.io/rmg/static/js/indoorSHMetro.35389781.chunk.js:1:295
    at Suspense
    at svg
    at c (https://railmapgen.github.io/rmg/static/js/AppRoot.01bd0b64.chunk.js:1:8675)
    at n (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:2800)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:150446
    at b (https://railmapgen.github.io/rmg/static/js/AppRoot.01bd0b64.chunk.js:1:9858)
    at div
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336559
    at section
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:150446
    at div
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:150446
    at div
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:150446
    at div
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336559
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:150446
    at pe (https://railmapgen.github.io/rmg/static/js/AppRoot.01bd0b64.chunk.js:1:81232)
    at n (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:2800)
    at Suspense
    at A (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:586533)
    at R (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:585792)
    at c (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:579266)
    at https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:263158
    at m (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:197461)
    at v (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:134588)
    at d (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:336770)
    at A (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:306379)
    at v (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:197987)
    at go (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:263761)
    at c (https://railmapgen.github.io/rmg/static/js/main.086a3174.js:2:576914)
    at b
Please try to refresh or re-import your configuration files. If the issue still persists, please consider upgrading your browser or submit an issue in [GitHub Issue](https://github.com/railmapgen/rmg/issues) with the detail shown above.

請嘗試重新整理或重新上載設定檔。如果問題仍然存在，請考慮更新你的瀏覽器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一個Issue並附上詳情。

请尝试刷新或或重新上传配置文件。如果问题仍然存在，请考虑更新您的浏览器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一个Issue并附上详情。

**Comment by wongchito** [comment]
你好 @749207106 ，

請使用最新版的Edge或Chrome，我們暫不支援較較之版本或其他瀏覽器。多謝。
