### ISSUE TITLE
RMG offline app issued with a log

### ISSUE THREAD

**Issue by deepinclub** [railmapgen/rmg#455]
Something went wrong.
详情
Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at b (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/AppRoot.675b2618.chunk.js:1:9855)
    at div
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:336553
    at section
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:336553
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:150440
    at div
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:336553
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:150440
    at div
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:336553
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:150440
    at div
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:336553
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:150440
    at pe (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/AppRoot.675b2618.chunk.js:1:81223)
    at n (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:2800)
    at Suspense
    at A (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:586527)
    at R (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:585786)
    at c (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:579260)
    at file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:263152
    at m (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:197455)
    at v (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:134582)
    at d (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:336764)
    at A (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:306373)
    at v (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:197981)
    at go (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:263755)
    at c (file:///C:/Users/27056/AppData/Local/Programs/rmg/resources/app.asar/build/static/js/main.455f9c7c.js:2:576908)
    at b
Please try to refresh or re-import your configuration files. If the issue still persists, please consider upgrading your browser or submit an issue in [GitHub Issue](https://github.com/railmapgen/rmg/issues) with the detail shown above.

請嘗試重新整理或重新上載設定檔。如果問題仍然存在，請考慮更新你的瀏覽器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一個Issue並附上詳情。

请尝试刷新或或重新上传配置文件。如果问题仍然存在，请考虑更新您的浏览器，或前往[GitHub Issue](https://github.com/railmapgen/rmg/issues)提交一个Issue并附上详情。

**Comment by thekingofcity** [comment]
Hi, thanks for reporting. However this is an known issue. You may restart the application after this error and new template will be shown correctly.

> Keep in mind there might be errors when you change the templates or canvas. You may restart the application and should see the changed railmap.

**Comment by deepinclub** [comment]
Problem still exists after a lot of times. We keep restarting, but it keeps crashing.

**Comment by thekingofcity** [comment]
So you're experiencing this error on every startup?

**Comment by deepinclub** [comment]
Every time while button is clicked. Does your app work correctly?

**Comment by thekingofcity** [comment]
Hi, although there will be error after button is clicked, the new template should be seen after a restart. Is that what you're facing right now?

**Comment by wongchito** [comment]
Hi @deepinclub , offline app has been rebuilt from the latest code base. Could you please try the new version and see if the issue still persists?

**Comment by thekingofcity** [comment]
Since there is no reply for a long time, I'm going to close this issue.
