### ISSUE TITLE
【bug】上海地铁风格下的非贯通支线与主线的换乘站报错

### ISSUE THREAD

**Issue by TNLHK** [railmapgen/rmg#598]
![屏幕截图 2023-11-21 120106](https://github.com/railmapgen/rmg/assets/81743463/112e2f49-65b0-432e-821a-1d7adb4d2bb0)
（我知道上海地铁目前还没有非贯通支线这种类型，但我强迫症犯了）
报错文本：

> TypeError: Cannot read properties of undefined (reading 'name')
> 
>     at ze (https://railmapgen.gitlab.io/rmg/assets/index-37273f4d.js:1:11619)
>     at g
>     at svg
>     at W (https://railmapgen.gitlab.io/rmg/assets/share-b656defc.js:1:107)
>     at Ie (https://railmapgen.gitlab.io/rmg/assets/index-37273f4d.js:1:10485)
>     at t (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:107557)
>     at div
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6186
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:132994
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:296137
>     at ni (https://railmapgen.gitlab.io/rmg/assets/app-router-7ed542c8.js:1:2997)
>     at div
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6186
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:132994
>     at section
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6186
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:132994
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:296137
>     at div
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6186
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:132994
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:296137
>     at div
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6186
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:132994
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:296137
>     at Fh (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:113843)
>     at ds (https://railmapgen.gitlab.io/rmg/assets/app-router-7ed542c8.js:11:113449)
>     at ys (https://railmapgen.gitlab.io/rmg/assets/app-router-7ed542c8.js:11:118099)
>     at Suspense
>     at t (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:107557)
>     at gv (https://railmapgen.gitlab.io/rmg/assets/react-4978cfa7.js:43:3231)
>     at Lm (https://railmapgen.gitlab.io/rmg/assets/react-4978cfa7.js:43:6390)
>     at div
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6186
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:132994
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:296137
>     at Tu (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:113406)
>     at rd (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:128134)
>     at yp (https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:134344)
>     at jh (https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:17560)
>     at Ly (https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:6406)
>     at T_ (https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:133665)
>     at A_ (https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:134792)
>     at https://railmapgen.gitlab.io/rmg/assets/chakra-ba5f36b3.js:16:247221
>     at nd (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:128039)
>     at _v (https://railmapgen.gitlab.io/rmg/assets/react-4978cfa7.js:43:5825)
>     at zm (https://railmapgen.gitlab.io/rmg/assets/react-4978cfa7.js:52:415)
>     at ud
>     at yi (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:1:62773)
>     at yh (https://railmapgen.gitlab.io/rmg/assets/index-469b7548.js:25:2877)

**Comment by thekingofcity** [comment]
没太理解是说的哪种拓扑关系... 方便发下右边画布的图吗？

**Comment by TNLHK** [comment]
> 没太理解是说的哪种拓扑关系... 方便发下右边画布的图吗？

（事实上这个截图可以直接从画廊里的上海地铁10号线获取）
![屏幕截图 2023-11-21 193322](https://github.com/railmapgen/rmg/assets/81743463/e94a2e8d-01b1-4df6-a183-f9e804474857)

**Comment by thekingofcity** [comment]
就是说没有进行任何更改的上海地铁10号线模板吗？我这边尝试下来的是可以正常工作的 :)

![image](https://github.com/railmapgen/rmg/assets/3353040/ec974985-1120-413e-bf7e-1f303a2aae4f)

**Comment by thekingofcity** [comment]
> > 就是说没有进行任何更改的上海地铁10号线模板吗？我这边尝试下来的是可以正常工作的 :)
> > ![image](https://user-images.githubusercontent.com/3353040/284581006-ec974985-1120-413e-bf7e-1f303a2aae4f.png)
> 
> 不是不作任何更改，是把龙溪路的Throught改为Non-throught

嗨，感谢报告问题，我们已经对其进行了修复，稍后您应该能在 5.14.13 版本上不再遇到此问题 :)

![image](https://github.com/railmapgen/rmg/assets/3353040/99b4b961-c025-43c8-8a56-285459287a72)
