### ISSUE TITLE
What can I Say?

### ISSUE THREAD

**Issue by CCD5070-05045GH** [railmapgen/rmg#664]
There is a Bug: Please try to refresh or re-import your configuration files. If the issue still persists, please consider upgrading your browser. Should you need any help, please contact us by submitting an issue in [GitHub Issue](https://github.com/railmapgen/rmg/issues) with the details shown below.

**Comment by wongchito** [comment]
Hi @CCD5070-05045GH ,

Please include the necessary information as per the error message’s instructions for our investigation. Thanks!

**Comment by yan3603522417** [comment]
2024.12.14晚，本人在编辑广州28号线的rmg时，线路图无法显示
（28号线规划很多，有两条支线，一条贯通，一条不贯通，不知和楼主是否一样？）
之后打开广14，正常了

**Comment by yan3603522417** [comment]
![微信截图_20241216132554](https://github.com/user-attachments/assets/a7dd5223-52ca-4ea5-a3da-d30894e01417)
![微信截图_20241216132926](https://github.com/user-attachments/assets/633d1b1b-4106-453d-993f-d7b0aeb0435d)

**Comment by GeorgeW547** [comment]
我在做都江堰M-TR旅游客运专线（未来成都低运量轨道交通L7线）是也遇到了这样子的问题，画了三条支线，全贯通，有两条两端均连接至主线，另一条只连接主线一端。我尝试过刷新网页、备份后重新导入项目和备份后清除历史记录再重新导入，这条消息都没有消退。（我的错误消息和TA的完全一样）

**Comment by yan3603522417** [comment]
Something went wrong!
请尝试刷新或者重新上传配置文件。如果问题仍然存在，请考虑更新您的浏览器。如需帮助或者联系我们，请前往 [GitHub Issue](https://github.com/railmapgen/rmg/issues) 提交一个 Issue 并附上详细信息。

详情
TypeError: Cannot read properties of undefined (reading 'indexOf')

    at Me (https://railmapgen.github.io/rmg/assets/index-DJ2RfKKL.js:1:18111)
    at svg
    at W (https://railmapgen.github.io/rmg/assets/share-B2Lv_hj8.js:1:107)
    at Je (https://railmapgen.github.io/rmg/assets/index-DJ2RfKKL.js:1:21882)
    at t (https://railmapgen.github.io/rmg/assets/index-Bbxj3dYA.js:10:26277)
    at div
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:142012
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:175032
    at Xr (https://railmapgen.github.io/rmg/assets/app-router-BLcHK67w.js:2:2704)
    at div
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:142012
    at section
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:142012
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:175032
    at div
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:142012
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:175032
    at div
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:142012
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:175032
    at Ih (https://railmapgen.github.io/rmg/assets/index-Bbxj3dYA.js:10:32357)
    at gi (https://railmapgen.github.io/rmg/assets/app-router-BLcHK67w.js:12:110947)
    at Ci (https://railmapgen.github.io/rmg/assets/app-router-BLcHK67w.js:12:115788)
    at Suspense
    at t (https://railmapgen.github.io/rmg/assets/index-Bbxj3dYA.js:10:26277)
    at Rm (https://railmapgen.github.io/rmg/assets/react-CMFWkwMo.js:34:13262)
    at Qv (https://railmapgen.github.io/rmg/assets/react-CMFWkwMo.js:34:17682)
    at div
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:142012
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:175032
    at af (https://railmapgen.github.io/rmg/assets/index-Bbxj3dYA.js:10:31918)
    at Df (https://railmapgen.github.io/rmg/assets/index-Bbxj3dYA.js:10:46359)
    at Yp (https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:18219)
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7257
    at WT (https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:7477)
    at QT (https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:17359)
    at r_ (https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:18669)
    at https://railmapgen.github.io/rmg/assets/chakra-BQCjpw4m.js:16:154944
    at $f (https://railmapgen.github.io/rmg/assets/index-Bbxj3dYA.js:10:46264)
    at jm (https://railmapgen.github.io/rmg/assets/react-CMFWkwMo.js:34:16814)
    at Kv (https://railmapgen.github.io/rmg/assets/react-CMFWkwMo.js:34:25956)
    at Uf
    at Hv (https://railmapgen.github.io/rmg/assets/react-CMFWkwMo.js:25:133792)
    at Fv (https://railmapgen.github.io/rmg/assets/react-CMFWkwMo.js:42:2959)

**Comment by yan3603522417** [comment]
我的广18远期也正常

**Comment by wongchito** [comment]
Hi @CCD5070-05045GH @yan3603522417 ,

請問閣下能否提供一份能導致錯誤發生的設定檔予我們以排解問題，或描述如何令錯誤重現。多謝！

**Comment by yan3603522417** [comment]
添加我的qq获取文件（就是上面这个号）



发自我的iPhone


------------------ Original ------------------
From: Chito Wong ***@***.***&gt;
Date: Tue,Jan 28,2025 11:34 PM
To: railmapgen/rmg ***@***.***&gt;
Cc: yan3603522417 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [railmapgen/rmg] What can I Say? (Issue #664)





 
Hi @CCD5070-05045GH @yan3603522417 ,
 
請問閣下能否提供一份能導致錯誤發生的設定檔予我們以排解問題，或描述如何令錯誤重現。多謝！

**Comment by wongchito** [comment]
Fixed in #708
