### ISSUE TITLE
关于铁路线路图生成器文件导入导出问题反馈与广州地铁环线风格模板添加申请

### ISSUE THREAD

**Issue by Jay20081229** [railmapgen/rmg#673]
铁路线路图生成器现在有个问题：我的文件3从镜像端下载后，无法导入官网端（见图1），却能在镜像端打开（见图2），无论多少次尝试、重置应用程序都没用。
麻烦官网及镜像网站都更新一下广州地铁的环线风格线路图模板，以广州地铁11号线（见文件4）为准，达到版本同步，以免镜像下载的路线图无法导入官网版。
广州地铁11号线路线图，链接见https://www.bilibili.com/video/BV1sBkdYCETp/以及https://baike.baidu.com/item/%E5%B9%BF%E5%B7%9E%E5%9C%B0%E9%93%8111%E5%8F%B7%E7%BA%BF/5285107?fr=ge_ala。
图1与图2：
[图片1与图片2.zip](https://github.com/user-attachments/files/18245554/1.2.zip)

文件3与文件4：
[文件3与文件4.zip](https://github.com/user-attachments/files/18245558/3.4.zip)

**Comment by Jay20081229** [comment]
链接①https://www.bilibili.com/video/BV1sBkdYCETp/

链接②https://baike.baidu.com/item/%E5%B9%BF%E5%B7%9E%E5%9C%B0%E9%93%8111%E5%8F%B7%E7%BA%BF/5285107?fr=ge_ala

链接应该是这两个，前面写的连在一起了，打开不了

**Comment by thekingofcity** [comment]
嗨，广州风格的环线正在加紧制作中。

另外，官网与镜像的版本已同步一致，感谢反馈 :)

**Comment by gray-husky** [comment]
同求Rail Map Generator支持环线

**Comment by gray-husky** [comment]
Thanks for supporting GZMTR loop line！I will provide feedback and suggestions after thorough use. @wongchito

**Comment by gray-husky** [comment]
when I change the line color，something wrong happens.
@wongchito 

Something went wrong!
Please try to refresh or re-import your configuration files. If the issue still persists, please consider upgrading your browser. Should you need any help, please contact us by submitting an issue in [GitHub Issue](https://github.com/railmapgen/rmg-palette/issues) with the details shown below.

請嘗試重新整理或重新上載設定檔。如果問題仍然存在，請考慮更新你的瀏覽器。如需協助或與我們聯絡，請前往 [GitHub Issue](https://github.com/railmapgen/rmg-palette/issues) 提交一個 Issue 並附以詳細資料。

请尝试刷新或者重新上传配置文件。如果问题仍然存在，请考虑更新您的浏览器。如需帮助或者联系我们，请前往 [GitHub Issue](https://github.com/railmapgen/rmg-palette/issues) 提交一个 Issue 并附上详细信息。

详情
TypeError: Failed to fetch dynamically imported module: http://localhost:5173/rmg-palette/assets/picker-view-CLRTc01Q.js

    at Lazy
    at Suspense
    at t (http://localhost:5173/rmg-palette/assets/index-CgzWA51A.js:10:27121)
    at Ky (http://localhost:5173/rmg-palette/assets/react-Xm5uCCSw.js:42:14644)
    at Yv (http://localhost:5173/rmg-palette/assets/react-Xm5uCCSw.js:42:18492)
    at div
    at http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:7257
    at http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:142385
    at http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:169320
    at Mc (http://localhost:5173/rmg-palette/assets/index-CgzWA51A.js:10:32761)
    at vd (http://localhost:5173/rmg-palette/assets/index-CgzWA51A.js:10:45279)
    at Rp (http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:18219)
    at http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:7257
    at gT (http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:7477)
    at PT (http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:17359)
    at $T (http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:18669)
    at http://localhost:5173/rmg-palette/assets/chakra-C7mz8WDx.js:16:155317
    at md (http://localhost:5173/rmg-palette/assets/index-CgzWA51A.js:10:45184)
    at nv (http://localhost:5173/rmg-palette/assets/react-Xm5uCCSw.js:42:17624)
    at Xv (http://localhost:5173/rmg-palette/assets/react-Xm5uCCSw.js:42:26766)
    at Sd
    at Kv (http://localhost:5173/rmg-palette/assets/react-Xm5uCCSw.js:33:32076)
    at Yh (http://localhost:5173/rmg-palette/assets/react-Xm5uCCSw.js:33:2959)

**Comment by wongchito** [comment]
Hi @gray-husky ,

Please provide the RMT instance (i.e. the URL of the website) that you're using. 

If possible, please provide a full screenshot for better support. 

Thanks!
